--- cargo-espflash/Cargo.toml.orig	2025-09-24 04:49:03 UTC
+++ cargo-espflash/Cargo.toml
@@ -32,7 +32,7 @@ toml           = "0.8.19"
 toml           = "0.8.19"
 
 [target.'cfg(unix)'.dependencies]
-cargo = { version = "0.85.0", features = ["vendored-openssl"] }
+cargo = { version = "0.85.0" }
 
 [target.'cfg(windows)'.dependencies]
 cargo = "0.85.0"
