--- esp-toolchain-bin-wrappers/gnu-riscv-binutils/Cargo.toml.orig	2025-09-28 13:42:05 UTC
+++ esp-toolchain-bin-wrappers/gnu-riscv-binutils/Cargo.toml
@@ -6,8 +6,8 @@ edition = "2021"
 # See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
 
 [dependencies]
-lazy_static = "1.5.0"
-libc = "0.2.175"
+lazy_static = "%%XTENSA_ESP_TOOLCHAIN_BIN_WRAPPERS_LAZY_STATIC_VERSION%%"
+libc = "%%XTENSA_ESP_TOOLCHAIN_BIN_WRAPPERS_LIBC_VERSION%%"
 
 [[bin]]
 name = "riscv-binutil-wrapper"
